# Generated by Django 5.0.3 on 2024-05-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='-', max_length=50, verbose_name='ID задачи'),
            preserve_default=False,
        ),
    ]
