# Generated by Django 5.0.3 on 2024-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя макета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='task_id',
            field=models.CharField(max_length=50, verbose_name='Id задачи'),
        ),
    ]
